#!/usr/bin/env python3
"""RREL production MIS dashboard (Flask + Postgres).

Vercel / production environment:

    DATABASE_URL          Postgres connection string (pooled Neon / Vercel Postgres URL)
    MIS_TIMEZONE          Plant timezone (default Asia/Kolkata)
    MIS_PUBLIC_ORIGIN     Public origin, e.g. https://your-app.vercel.app
    MIS_SECURE_COOKIES    Set to 1 when serving HTTPS

Local: `python main.py --host 127.0.0.1 --port 8765` with DATABASE_URL set.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import secrets
import time
from datetime import datetime, timedelta, timezone
from functools import wraps
from pathlib import Path
from urllib.parse import unquote
from zoneinfo import ZoneInfo

import psycopg
from flask import Flask, Response, request, send_from_directory
from psycopg.rows import dict_row

ROOT = Path(__file__).resolve().parent
MAX_BODY_BYTES = 2 * 1024 * 1024
SESSION_SECONDS = 12 * 60 * 60
PBKDF2_ITERATIONS = 210_000
MIS_TIMEZONE = os.environ.get("MIS_TIMEZONE", "Asia/Kolkata")
PUBLIC_ORIGIN = os.environ.get("MIS_PUBLIC_ORIGIN", "").rstrip("/")
SECURE_COOKIES = os.environ.get("MIS_SECURE_COOKIES", "0") == "1"
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
USERNAME_RE = re.compile(r"^[a-zA-Z0-9._-]{3,24}$")
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "no-referrer",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
    "Content-Security-Policy": (
        "default-src 'self'; script-src 'self' 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "font-src https://fonts.gstatic.com; img-src 'self' data:; "
        "connect-src 'self'; base-uri 'none'; form-action 'self'"
    ),
}
SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS entries (
        entry_date TEXT PRIMARY KEY,
        payload TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS accounts (
        username TEXT PRIMARY KEY,
        payload TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        username TEXT NOT NULL,
        actor_username TEXT,
        created_at BIGINT NOT NULL,
        expires_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS login_attempts (
        username TEXT PRIMARY KEY,
        failures INTEGER NOT NULL,
        locked_until BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        occurred_at TEXT NOT NULL,
        actor TEXT,
        action TEXT NOT NULL,
        entity TEXT NOT NULL,
        entity_id TEXT,
        detail TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_audit_occurred_at ON audit_log(occurred_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at)",
)

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = MAX_BODY_BYTES
_db_ready = False


class ApiError(Exception):
    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status
        self.message = message


def utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def active_shift_context(now: datetime | None = None) -> dict:
    zone = ZoneInfo(MIS_TIMEZONE)
    local = now.astimezone(zone) if now else datetime.now(zone)
    hour = local.hour
    if 6 <= hour < 14:
        shift, start, end = "A", "06:00", "14:00"
        operational_date = local.date()
    elif 14 <= hour < 22:
        shift, start, end = "B", "14:00", "22:00"
        operational_date = local.date()
    else:
        shift, start, end = "C", "22:00", "06:00"
        operational_date = local.date() - timedelta(days=1) if hour < 6 else local.date()
    return {
        "date": operational_date.isoformat(),
        "shift": shift,
        "hours": f"{start} – {end}",
        "timezone": MIS_TIMEZONE,
        "serverTime": local.isoformat(),
    }


def database_url() -> str:
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        raise ApiError(503, "Database unavailable")
    return url


def connect() -> psycopg.Connection:
    # prepare_threshold=None is required for Neon/Vercel pooled (PgBouncer) URLs.
    return psycopg.connect(database_url(), row_factory=dict_row, prepare_threshold=None)


def initialize_database() -> None:
    global _db_ready
    if _db_ready:
        return
    with connect() as connection:
        for statement in SCHEMA_STATEMENTS:
            connection.execute(statement)
    _db_ready = True


def password_credential(password: str) -> dict:
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ITERATIONS)
    return {"passwordHash": digest.hex(), "salt": salt.hex(), "iterations": PBKDF2_ITERATIONS}


def valid_password(password: str) -> bool:
    return len(password) >= 8 and any(c.isalpha() for c in password) and any(c.isdigit() for c in password)


def verify_password(password: str, account: dict) -> bool:
    try:
        iterations = int(account.get("iterations", 0))
        salt = bytes.fromhex(account["salt"])
        expected = account["passwordHash"]
        if iterations <= 0 or len(salt) < 8:
            return False
        actual = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, iterations).hex()
        return hmac.compare_digest(actual, expected)
    except (KeyError, TypeError, ValueError):
        return False


def public_account(account: dict) -> dict:
    return {k: v for k, v in account.items() if k not in {"passwordHash", "salt", "iterations"}}


def load_account(connection: psycopg.Connection, username: str) -> dict | None:
    row = connection.execute("SELECT payload FROM accounts WHERE username = %s", (username.lower(),)).fetchone()
    return json.loads(row["payload"]) if row else None


def store_account(connection: psycopg.Connection, username: str, account: dict) -> None:
    username = username.lower()
    account["username"] = username
    connection.execute(
        """INSERT INTO accounts(username,payload,updated_at) VALUES (%s,%s,%s)
           ON CONFLICT(username) DO UPDATE SET payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at""",
        (username, json.dumps(account, ensure_ascii=False), utc_iso()),
    )


def audit(connection, actor, action, entity, entity_id=None, detail=None) -> None:
    connection.execute(
        "INSERT INTO audit_log(occurred_at,actor,action,entity,entity_id,detail) VALUES (%s,%s,%s,%s,%s,%s)",
        (utc_iso(), actor, action, entity, entity_id, json.dumps(detail or {}, ensure_ascii=False)),
    )


def json_response(value, status=200, cookie: tuple[str, str] | None = None) -> Response:
    body = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    response = Response(body, status=status, mimetype="application/json; charset=utf-8")
    response.headers["Cache-Control"] = "no-store"
    if cookie:
        name, value = cookie
        max_age = 0 if value == "" else SESSION_SECONDS
        response.set_cookie(
            name,
            value,
            max_age=max_age,
            path="/",
            httponly=True,
            samesite="Strict",
            secure=SECURE_COOKIES,
        )
    return response


def no_content(clear_session: bool = False) -> Response:
    response = Response(status=204)
    response.headers["Cache-Control"] = "no-store"
    if clear_session:
        response.set_cookie(
            "mis_session",
            "",
            max_age=0,
            path="/",
            httponly=True,
            samesite="Strict",
            secure=SECURE_COOKIES,
        )
    return response


def read_json_object(allow_empty: bool = False) -> dict:
    raw = request.get_data(cache=True) or b""
    if not raw:
        if allow_empty:
            return {}
        raise ApiError(400, "Request body must be between 1 byte and 2 MB")
    if len(raw) > MAX_BODY_BYTES:
        raise ApiError(400, "Request body must be between 1 byte and 2 MB")
    try:
        value = json.loads(raw.decode())
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ApiError(400, "Request body must be valid JSON") from exc
    if not isinstance(value, dict):
        raise ApiError(400, "Request body must be a JSON object")
    return value


def reject_cross_site_write() -> None:
    if request.headers.get("Sec-Fetch-Site", "") == "cross-site":
        raise ApiError(403, "Cross-site requests are not allowed")
    origin = request.headers.get("Origin")
    allowed_origin = PUBLIC_ORIGIN or request.host_url.rstrip("/")
    if origin and allowed_origin and origin.rstrip("/") != allowed_origin:
        raise ApiError(403, "Invalid request origin")


def mutating(fn):
    @wraps(fn)
    def wrapped(*args, **kwargs):
        reject_cross_site_write()
        return fn(*args, **kwargs)

    return wrapped


def token_hash() -> str | None:
    value = request.cookies.get("mis_session")
    return hashlib.sha256(value.encode()).hexdigest() if value else None


def current_session(connection):
    hashed = token_hash()
    if not hashed:
        return None
    now = int(time.time())
    connection.execute("DELETE FROM sessions WHERE expires_at <= %s", (now,))
    row = connection.execute(
        "SELECT token_hash,username,actor_username,expires_at FROM sessions WHERE token_hash=%s",
        (hashed,),
    ).fetchone()
    if not row:
        return None
    account = load_account(connection, row["username"])
    return (row, account) if account else None


def require_session(connection, master=False):
    current = current_session(connection)
    if not current:
        raise ApiError(401, "Please sign in")
    if master and current[1].get("role") != "master":
        raise ApiError(403, "Master access is required")
    return current


def session_view(connection, row, account):
    value = {
        "username": row["username"],
        "displayName": account.get("displayName") or row["username"],
        "role": account.get("role", "user"),
        "expiresAt": row["expires_at"] * 1000,
    }
    if row["actor_username"]:
        actor = load_account(connection, row["actor_username"])
        if actor:
            value["impersonator"] = {
                "username": row["actor_username"],
                "displayName": actor.get("displayName") or row["actor_username"],
                "role": actor.get("role", "master"),
                "expiresAt": row["expires_at"] * 1000,
            }
    return value


def create_session(connection, username, actor=None):
    token = secrets.token_urlsafe(32)
    hashed = hashlib.sha256(token.encode()).hexdigest()
    now, expires = int(time.time()), int(time.time()) + SESSION_SECONDS
    connection.execute(
        "INSERT INTO sessions(token_hash,username,actor_username,created_at,expires_at) VALUES (%s,%s,%s,%s,%s)",
        (hashed, username.lower(), actor, now, expires),
    )
    row = connection.execute(
        "SELECT token_hash,username,actor_username,expires_at FROM sessions WHERE token_hash=%s",
        (hashed,),
    ).fetchone()
    return session_view(connection, row, load_account(connection, username)), token


@app.before_request
def ensure_database():
    if request.path == "/api/health":
        return
    try:
        initialize_database()
    except (ApiError, psycopg.Error) as exc:
        if isinstance(exc, ApiError):
            raise
        raise ApiError(503, "Database unavailable") from exc


@app.after_request
def add_security_headers(response: Response) -> Response:
    for name, value in SECURITY_HEADERS.items():
        response.headers.setdefault(name, value)
    return response


@app.errorhandler(ApiError)
def handle_api_error(exc: ApiError):
    return json_response({"error": exc.message}, exc.status)


@app.errorhandler(404)
def handle_not_found(_exc):
    if request.path.startswith("/api/"):
        return json_response({"error": "Unknown API endpoint"}, 404)
    return Response("Not found", status=404)


@app.errorhandler(413)
def handle_too_large(_exc):
    return json_response({"error": "Request body must be between 1 byte and 2 MB"}, 400)


@app.get("/")
@app.get("/index.html")
def dashboard():
    return send_from_directory(ROOT / "templates", "index.html")


@app.get("/api/health")
def api_health():
    try:
        initialize_database()
        with connect() as connection:
            connection.execute("SELECT 1")
        return json_response({"ok": True, "version": "2.0", "database": "postgres"})
    except (ApiError, psycopg.Error):
        return json_response({"error": "Database unavailable"}, 503)


@app.get("/api/auth/status")
def api_auth_status():
    with connect() as connection:
        has_accounts = connection.execute("SELECT 1 FROM accounts LIMIT 1").fetchone() is not None
        current = current_session(connection)
        session = session_view(connection, *current) if current else None
    return json_response({"hasAccounts": has_accounts, "session": session})


@app.get("/api/access")
def api_access():
    with connect() as connection:
        current = require_session(connection)
        context = active_shift_context()
        context["role"] = current[1].get("role", "user")
        context["canManageAll"] = context["role"] == "master"
    return json_response(context)


@app.get("/api/entries")
def api_entries():
    with connect() as connection:
        require_session(connection)
        rows = connection.execute("SELECT entry_date,payload FROM entries ORDER BY entry_date").fetchall()
    return json_response({row["entry_date"]: json.loads(row["payload"]) for row in rows})


@app.get("/api/accounts")
def api_list_accounts():
    with connect() as connection:
        require_session(connection, master=True)
        rows = connection.execute("SELECT username,payload FROM accounts ORDER BY username").fetchall()
    return json_response({row["username"]: public_account(json.loads(row["payload"])) for row in rows})


@app.get("/api/audit")
def api_audit():
    with connect() as connection:
        require_session(connection, master=True)
        rows = connection.execute(
            "SELECT id,occurred_at,actor,action,entity,entity_id,detail FROM audit_log ORDER BY id DESC LIMIT 200"
        ).fetchall()
    return json_response(
        [
            {
                "id": row["id"],
                "occurredAt": row["occurred_at"],
                "actor": row["actor"],
                "action": row["action"],
                "entity": row["entity"],
                "entityId": row["entity_id"],
                "detail": json.loads(row["detail"] or "{}"),
            }
            for row in rows
        ]
    )


@app.get("/api/system")
def api_system():
    with connect() as connection:
        require_session(connection, master=True)
        size_row = connection.execute("SELECT pg_database_size(current_database()) AS size").fetchone()
        values = {
            "entries": connection.execute("SELECT COUNT(*) AS n FROM entries").fetchone()["n"],
            "accounts": connection.execute("SELECT COUNT(*) AS n FROM accounts").fetchone()["n"],
            "auditEvents": connection.execute("SELECT COUNT(*) AS n FROM audit_log").fetchone()["n"],
            "databaseBytes": int(size_row["size"]) if size_row else 0,
        }
    return json_response(values)


@app.get("/api/backup")
def api_backup():
    with connect() as connection:
        current = require_session(connection, master=True)
        audit(connection, current[0]["username"], "backup", "database")
        accounts = {
            row["username"]: json.loads(row["payload"])
            for row in connection.execute("SELECT username,payload FROM accounts ORDER BY username").fetchall()
        }
        entries = {
            row["entry_date"]: json.loads(row["payload"])
            for row in connection.execute("SELECT entry_date,payload FROM entries ORDER BY entry_date").fetchall()
        }
        events = [
            {
                "id": row["id"],
                "occurredAt": row["occurred_at"],
                "actor": row["actor"],
                "action": row["action"],
                "entity": row["entity"],
                "entityId": row["entity_id"],
                "detail": json.loads(row["detail"] or "{}"),
            }
            for row in connection.execute(
                "SELECT id,occurred_at,actor,action,entity,entity_id,detail FROM audit_log ORDER BY id"
            ).fetchall()
        ]
    body = json.dumps(
        {"accounts": accounts, "entries": entries, "auditLog": events},
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode()
    filename = f"rrel-mis-backup-{datetime.now().strftime('%Y%m%d-%H%M%S')}.json"
    response = Response(body, mimetype="application/json")
    response.headers["Content-Disposition"] = f'attachment; filename="{filename}"'
    response.headers["Cache-Control"] = "no-store"
    return response


@app.post("/api/auth/setup")
@mutating
def api_auth_setup():
    body = read_json_object(allow_empty=True)
    username = str(body.get("username", "")).strip().lower()
    name, password = str(body.get("displayName", "")).strip()[:60], str(body.get("password", ""))
    if not USERNAME_RE.fullmatch(username) or not name or not valid_password(password):
        raise ApiError(400, "Enter a valid name, username, and strong password")
    with connect() as connection:
        if connection.execute("SELECT 1 FROM accounts LIMIT 1").fetchone():
            raise ApiError(409, "Initial setup is already complete")
        account = {
            "username": username,
            "displayName": name,
            "role": "master",
            "createdAt": utc_iso(),
            **password_credential(password),
        }
        store_account(connection, username, account)
        audit(connection, username, "setup", "account", username)
        session, token = create_session(connection, username)
    return json_response({"session": session}, 201, ("mis_session", token))


@app.post("/api/bootstrap/import")
@mutating
def api_bootstrap_import():
    body = read_json_object(allow_empty=True)
    accounts, entries = body.get("accounts", {}), body.get("entries", {})
    if not isinstance(accounts, dict) or not isinstance(entries, dict) or len(accounts) > 50 or len(entries) > 10000:
        raise ApiError(400, "Invalid import payload")
    with connect() as connection:
        if connection.execute("SELECT 1 FROM accounts LIMIT 1").fetchone():
            raise ApiError(409, "Initial setup is already complete")
        valid_accounts = []
        for username, account in accounts.items():
            key = str(username).lower()
            if not USERNAME_RE.fullmatch(key) or not isinstance(account, dict) or not all(
                k in account for k in ("passwordHash", "salt", "iterations")
            ):
                raise ApiError(400, "Local account data is invalid")
            valid_accounts.append((key, dict(account)))
        if valid_accounts and not any(account.get("role") == "master" for _, account in valid_accounts):
            raise ApiError(400, "Imported accounts must include a master")
        for username, account in valid_accounts:
            store_account(connection, username, account)
        imported_entries = 0
        for entry_date, payload in entries.items():
            if DATE_RE.fullmatch(str(entry_date)) and isinstance(payload, dict):
                connection.execute(
                    """INSERT INTO entries(entry_date,payload,updated_at) VALUES (%s,%s,%s)
                       ON CONFLICT(entry_date) DO UPDATE SET payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at""",
                    (entry_date, json.dumps(payload, ensure_ascii=False), utc_iso()),
                )
                imported_entries += 1
        if valid_accounts:
            audit(connection, None, "import", "database", detail={"accounts": len(valid_accounts), "entries": imported_entries})
    return json_response({"ok": True, "accounts": len(valid_accounts), "entries": imported_entries})


@app.post("/api/auth/login")
@mutating
def api_auth_login():
    body = read_json_object(allow_empty=True)
    username, password, now = str(body.get("username", "")).strip().lower(), str(body.get("password", "")), int(time.time())
    with connect() as connection:
        attempt = connection.execute(
            "SELECT failures,locked_until FROM login_attempts WHERE username=%s", (username,)
        ).fetchone()
        if attempt and attempt["locked_until"] > now:
            raise ApiError(429, "Too many attempts. Try again later")
        account = load_account(connection, username)
        if not account or not verify_password(password, account):
            failures = (attempt["failures"] if attempt else 0) + 1
            locked = now + min(30, 5 * (2 ** max(0, failures - 5))) * 60 if failures >= 5 else 0
            connection.execute(
                """INSERT INTO login_attempts(username,failures,locked_until) VALUES (%s,%s,%s)
                   ON CONFLICT(username) DO UPDATE SET failures=EXCLUDED.failures,locked_until=EXCLUDED.locked_until""",
                (username, failures, locked),
            )
            audit(connection, username or None, "login_failed", "session")
            connection.commit()
            raise ApiError(401, "Incorrect username or password")
        connection.execute("DELETE FROM login_attempts WHERE username=%s", (username,))
        session, token = create_session(connection, username)
        audit(connection, username, "login", "session")
    return json_response({"session": session}, cookie=("mis_session", token))


@app.post("/api/auth/logout")
@mutating
def api_auth_logout():
    with connect() as connection:
        current = current_session(connection)
        if current:
            audit(connection, current[0]["username"], "logout", "session")
            connection.execute("DELETE FROM sessions WHERE token_hash=%s", (current[0]["token_hash"],))
    return no_content(clear_session=True)


@app.post("/api/auth/password")
@mutating
def api_auth_password():
    body = read_json_object(allow_empty=True)
    old, new = str(body.get("currentPassword", "")), str(body.get("newPassword", ""))
    if not valid_password(new) or new == old:
        raise ApiError(400, "Choose a different strong password")
    with connect() as connection:
        current = require_session(connection)
        row, account = current
        if not verify_password(old, account):
            raise ApiError(403, "Current password is incorrect")
        account.update(password_credential(new))
        store_account(connection, row["username"], account)
        audit(connection, row["username"], "password_changed", "account", row["username"])
    return json_response({"ok": True})


@app.post("/api/accounts")
@mutating
def api_create_account():
    body = read_json_object(allow_empty=True)
    username = str(body.get("username", "")).strip().lower()
    name, password = str(body.get("displayName", "")).strip()[:60], str(body.get("password", ""))
    role = body.get("role") if body.get("role") in {"user", "master"} else "user"
    if not USERNAME_RE.fullmatch(username) or not name or not valid_password(password):
        raise ApiError(400, "Enter a valid name, username, and strong password")
    with connect() as connection:
        current = require_session(connection, master=True)
        if load_account(connection, username):
            raise ApiError(409, "That username already exists")
        account = {
            "username": username,
            "displayName": name,
            "role": role,
            "createdAt": utc_iso(),
            **password_credential(password),
        }
        store_account(connection, username, account)
        audit(connection, current[0]["username"], "created", "account", username, {"role": role})
    return json_response({"account": public_account(account)}, 201)


@app.post("/api/auth/impersonate/<username>")
@mutating
def api_impersonate(username: str):
    username = unquote(username).lower()
    with connect() as connection:
        current = require_session(connection, master=True)
        row = current[0]
        target = load_account(connection, username)
        if not target:
            raise ApiError(404, "Account not found")
        actor = row["actor_username"] or row["username"]
        connection.execute(
            "UPDATE sessions SET username=%s,actor_username=%s WHERE token_hash=%s",
            (username, actor, row["token_hash"]),
        )
        audit(connection, actor, "impersonated", "account", username)
        updated = connection.execute(
            "SELECT token_hash,username,actor_username,expires_at FROM sessions WHERE token_hash=%s",
            (row["token_hash"],),
        ).fetchone()
        session = session_view(connection, updated, target)
    return json_response({"session": session})


@app.post("/api/auth/stop-impersonation")
@mutating
def api_stop_impersonation():
    with connect() as connection:
        current = require_session(connection)
        row = current[0]
        actor = row["actor_username"]
        if not actor:
            raise ApiError(409, "Not impersonating an account")
        account = load_account(connection, actor)
        connection.execute(
            "UPDATE sessions SET username=%s,actor_username=NULL WHERE token_hash=%s",
            (actor, row["token_hash"]),
        )
        audit(connection, actor, "impersonation_stopped", "session")
        updated = connection.execute(
            "SELECT token_hash,username,actor_username,expires_at FROM sessions WHERE token_hash=%s",
            (row["token_hash"],),
        ).fetchone()
        session = session_view(connection, updated, account)
    return json_response({"session": session})


@app.patch("/api/me")
@mutating
def api_patch_me():
    body = read_json_object()
    name = str(body.get("displayName", "")).strip()[:60]
    if not name:
        raise ApiError(400, "Name cannot be empty")
    with connect() as connection:
        row, account = require_session(connection)
        account["displayName"] = name
        store_account(connection, row["username"], account)
        audit(connection, row["username"], "updated", "profile", row["username"])
    return json_response({"account": public_account(account)})


@app.patch("/api/accounts/<username>")
@mutating
def api_patch_account(username: str):
    body = read_json_object()
    username = unquote(username).lower()
    with connect() as connection:
        current = require_session(connection, master=True)
        account = load_account(connection, username)
        if not account:
            raise ApiError(404, "Account not found")
        name = str(body.get("displayName", account.get("displayName", username))).strip()[:60]
        role = body.get("role", account.get("role", "user"))
        if not name or role not in {"user", "master"}:
            raise ApiError(400, "Invalid account details")
        if account.get("role") == "master" and role != "master":
            rows = connection.execute("SELECT payload FROM accounts").fetchall()
            if sum(json.loads(row["payload"]).get("role") == "master" for row in rows) <= 1:
                raise ApiError(409, "The last master cannot be demoted")
        account.update({"displayName": name, "role": role})
        store_account(connection, username, account)
        audit(connection, current[0]["username"], "updated", "account", username, {"role": role})
    return json_response({"account": public_account(account)})


@app.put("/api/entries/<entry_date>")
@mutating
def api_put_entry(entry_date: str):
    payload = read_json_object()
    if not DATE_RE.fullmatch(entry_date):
        raise ApiError(400, "Entry date must use YYYY-MM-DD")
    with connect() as connection:
        current = require_session(connection)
        role = current[1].get("role", "user")
        accepted_shift = None
        if role != "master":
            access = active_shift_context()
            accepted_shift = access["shift"]
            if entry_date != access["date"]:
                raise ApiError(403, f"Users may edit only the active {accepted_shift} shift sheet for {access['date']}")
            shifts = payload.get("shifts")
            if not isinstance(shifts, dict) or not isinstance(shifts.get(accepted_shift), dict):
                raise ApiError(400, "The active shift sheet is missing")
            existing_row = connection.execute("SELECT payload FROM entries WHERE entry_date=%s", (entry_date,)).fetchone()
            stored = json.loads(existing_row["payload"]) if existing_row else {
                "date": entry_date,
                "month": payload.get("month"),
                "year": payload.get("year"),
                "shifts": {},
            }
            stored.setdefault("shifts", {})[accepted_shift] = shifts[accepted_shift]
            stored["updatedAt"] = payload.get("updatedAt") or utc_iso()
            stored["updatedBy"] = current[0]["username"]
            stored["updatedShift"] = accepted_shift
            payload = stored
        else:
            if not isinstance(payload.get("shifts"), dict):
                raise ApiError(400, "Production shifts are missing")
            payload["updatedBy"] = current[0]["username"]
        connection.execute(
            """INSERT INTO entries(entry_date,payload,updated_at) VALUES (%s,%s,%s)
               ON CONFLICT(entry_date) DO UPDATE SET payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at""",
            (entry_date, json.dumps(payload, ensure_ascii=False), utc_iso()),
        )
        audit(connection, current[0]["username"], "saved", "entry", entry_date, {"shift": accepted_shift or "ALL", "role": role})
    return json_response({"ok": True, "entryDate": entry_date, "acceptedShift": accepted_shift or "ALL"})


@app.delete("/api/entries/<entry_date>")
@mutating
def api_delete_entry(entry_date: str):
    if not DATE_RE.fullmatch(entry_date):
        raise ApiError(400, "Entry date must use YYYY-MM-DD")
    with connect() as connection:
        current = require_session(connection, master=True)
        connection.execute("DELETE FROM entries WHERE entry_date=%s", (entry_date,))
        audit(connection, current[0]["username"], "deleted", "entry", entry_date)
    return no_content()


@app.delete("/api/accounts/<username>")
@mutating
def api_delete_account(username: str):
    username = unquote(username).lower()
    with connect() as connection:
        current = require_session(connection, master=True)
        if username in {current[0]["username"], current[0]["actor_username"]}:
            raise ApiError(409, "You cannot remove your active account")
        account = load_account(connection, username)
        if not account:
            raise ApiError(404, "Account not found")
        if account.get("role") == "master":
            rows = connection.execute("SELECT payload FROM accounts").fetchall()
            if sum(json.loads(row["payload"]).get("role") == "master" for row in rows) <= 1:
                raise ApiError(409, "The last master cannot be removed")
        connection.execute("DELETE FROM sessions WHERE username=%s OR actor_username=%s", (username, username))
        connection.execute("DELETE FROM accounts WHERE username=%s", (username,))
        audit(connection, current[0]["username"], "deleted", "account", username)
    return no_content()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the RREL MIS dashboard")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()
    initialize_database()
    print(f"RREL MIS running at http://{args.host}:{args.port}", flush=True)
    app.run(host=args.host, port=args.port)


if __name__ == "__main__":
    main()
